// Generated by CoffeeScript 2.5.1
(function() {
  var Client, client, config, parentID, token, voiceID;

  ({Client} = require('discord.js'));

  client = new Client();

  ({token, voiceID, parentID} = require("./config.json"));

  client.login(token);

  client.on('ready', function() {
    return console.log("Ready!");
  });

  client.on('voiceStateUpdate', function(oldState, newState) {
    if (!oldState.guild.channels.cache.has(voiceID) || !oldState.guild.channels.cache.has(voiceID)) {
      throw Error("Не указано либо айди канала, либо айди категории");
    }
    if (newState.channelID === voiceID) {
      newState.guild.channels.create('Private', {
        type: "VOICE",
        parent: parentID,
        permissionOverwrites: [
          {
            id: newState.guild.id,
            allow: ["VIEW_CHANNEL"]
          },
          {
            id: newState.member.id,
            allow: ["VIEW_CHANNEL",
          "MANAGE_CHANNELS"]
          }
        ]
      }).then(function(ch) {
        return newState.setChannel(ch);
      });
    }
    if (oldState.channel && !oldState.channel.members.size && oldState.channel.parentID === parentID && oldState.channelID !== voiceID) {
      return oldState.channel.delete();
    }
  });

}).call(this);
